#!/usr/bin/env node
/**
 * Generates token-mgmt-remittance-catalog.json (≥150 entries) from plan spec §9.
 * Run: node build-catalog.mjs
 */
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, 'token-mgmt-remittance-catalog.json');
const SCREEN = {
  dash: 'token-mgmt-remittance.dashboard-enhanced',
  wallet: 'token-mgmt-remittance.wallet-enhanced',
  notif: 'token-mgmt-remittance.notifications',
  send: 'token-mgmt-remittance.send-enhanced',
};

const BE = 'Proposed contract — not implemented in prototype';

function entry({
  id,
  featureRow = null,
  featureName = '',
  label,
  status = 'live',
  screen,
  selector,
  presenterNote,
  what,
  frontend,
  backend,
  example = 'N/A',
  seeAlso,
}) {
  const e = {
    id,
    featureRow,
    featureName,
    label,
    status,
    screen,
    selector,
    panel: {
      what,
      frontend,
      backend: backend || BE,
      example,
    },
  };
  if (presenterNote) e.presenterNote = presenterNote;
  if (seeAlso?.length) e.seeAlso = seeAlso;
  return e;
}

/** @type {ReturnType<typeof entry>[]} */
const dashboard = [
  entry({ id: 'dashboard.user.displayName', label: 'Welcome headline', selector: '.page-title', screen: SCREEN.dash, what: 'Greeting headline showing the authenticated user\'s display name (“Jane Smith”).', frontend: 'Prototype: static text in HTML. Production: hydrate from session after login — GET /api/users/me → user.displayName. Fallback: email local-part.', backend: 'GET /api/users/me → { "displayName": "Jane Smith", "email": "jane@example.com" }', example: { displayName: 'Jane Smith' } }),
  entry({ id: 'dashboard.user.subtitle', label: 'Page subtitle', selector: '.page-subtitle', screen: SCREEN.dash, what: 'Supporting tagline under the welcome header; sets context for impact tracking.', frontend: 'Static copy in HTML / CMS string key dashboard.subtitle.', backend: 'Optional CMS GET /api/copy/dashboard or hardcoded i18n.', example: 'One Flow. Many Lives. - Track your impact and manage your contributions' }),
  entry({ id: 'dashboard.impact.portfolio.value', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'Total Portfolio (KPI)', selector: '.impact-card[aria-label*="Total portfolio"] .impact-value', screen: SCREEN.dash, what: 'Total portfolio value across all UNERA assets in display currency (CAD/USD per user pref).', frontend: 'Prototype: static $10,240. Production: sum accounts[].balanceFiat from balances API; format with Intl.NumberFormat.', backend: 'GET /api/wallet/balances → { "portfolio": { "totalFiat": 10240, "currency": "CAD" } }', example: { totalFiat: 10240, currency: 'CAD' }, seeAlso: ['wallet.portfolio.total'] }),
  entry({ id: 'dashboard.impact.portfolio.walletHint', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'Portfolio wallet hint', selector: '.impact-card[aria-label*="Total portfolio"] .impact-detail', screen: SCREEN.dash, what: 'Truncated connected wallet address + primary network label for trust/context.', frontend: 'Prototype: hardcoded 0x742d...3a8f • Ethereum. Production: localStorage.walletAddress or GET /api/wallet/primary → truncate + resolve chain name.', backend: 'GET /api/wallet/primary → { "address": "0x742d35Cc…", "network": "ethereum" }', example: { address: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb0', network: 'ethereum' } }),
  entry({ id: 'dashboard.impact.portfolio.sparkline', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Portfolio sparkline', selector: '.impact-card[aria-label*="Total portfolio"] .impact-sparkline', screen: SCREEN.dash, what: 'Mini 30-day portfolio trend line (SVG polyline); visual summary only.', frontend: 'Prototype: static SVG points. Production: map GET /api/portfolio/history?range=30d → normalize Y coords into viewBox.', backend: 'GET /api/portfolio/history?range=30d → { "points": [{ "date": "2026-05-01", "value": 9800 }, …] }', example: { points: [{ date: '2026-05-19', value: 10240 }] } }),
  entry({ id: 'dashboard.impact.portfolio.trend', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Portfolio trend pill', selector: '.impact-card[aria-label*="Total portfolio"] .impact-trend', screen: SCREEN.dash, what: 'Period delta label (e.g. “+$2,400 this month”) with up/down styling.', frontend: 'Compute current - startOfPeriod from history API; apply .impact-trend / --fin-up classes.', backend: 'Same history endpoint; server may return changeAbs, changePct, period.', example: { changeAbs: 2400, period: 'month', direction: 'up' } }),
  entry({ id: 'dashboard.impact.portfolio.infoTooltip', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Portfolio info (i)', selector: '.impact-card[aria-label*="Total portfolio"] .info-tooltip', screen: SCREEN.dash, what: 'Native UI info affordance (i) — product copy explaining KPI semantics (distinct from data-mapping panel).', frontend: 'data-tooltip attribute in HTML; optional CMS.', backend: 'N/A — copy deck.', example: 'Your total portfolio value across all assets' }),
  entry({ id: 'dashboard.impact.yield.value', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'Yield Generated (KPI)', selector: '.impact-card[aria-label*="Yield generated"] .impact-value', screen: SCREEN.dash, what: 'Cumulative yield generated from stablecoin reserves allocated to impact.', frontend: 'Static $486.50 in prototype. Production: GET /api/portfolio/summary → yield.totalFiat.', backend: 'GET /api/portfolio/summary → { "yield": { "totalFiat": 486.5 } }', example: { yield: { totalFiat: 486.5 } } }),
  entry({ id: 'dashboard.impact.yield.trend', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Yield trend pill', selector: '.impact-card[aria-label*="Yield generated"] .impact-trend', screen: SCREEN.dash, what: 'Recent yield accrual trend (e.g. “+$42 this week”).', frontend: 'Derived from yield history aggregation.', backend: 'GET /api/yield/history?range=7d', example: { changeAbs: 42, period: 'week' } }),
  entry({ id: 'dashboard.impact.donations.value', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'Total Donations (KPI)', selector: '.impact-card[aria-label*="Total donations"] .impact-value', screen: SCREEN.dash, what: 'Lifetime donation total to Humanity Centres (informational KPI — not row 44 scope).', frontend: 'Static $5,240. Production: GET /api/donations/summary → totalFiat.', backend: 'GET /api/donations/summary → { "totalFiat": 5240, "centresCount": 3 }', example: { totalFiat: 5240, centresCount: 3 } }),
  entry({ id: 'dashboard.impact.donations.detail', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Donations centres count', selector: '.impact-card[aria-label*="Total donations"] .impact-detail', screen: SCREEN.dash, what: 'Secondary stat — number of centres supported.', frontend: 'From donations summary centresCount.', backend: 'Included in donations summary payload.', example: { centresCount: 3 } }),
  entry({ id: 'dashboard.impact.lives.value', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Lives Impacted (KPI)', selector: '.impact-card[aria-label*="Lives impacted"] .impact-value', screen: SCREEN.dash, what: 'Estimated impact reach metric (model-driven, not on-chain).', frontend: 'Static 1,240+. Production: impact metrics service.', backend: 'GET /api/impact/lives → { "estimate": 1240, "display": "1,240+" }', example: { estimate: 1240 } }),
  entry({ id: 'dashboard.actions.wallet', featureRow: 35, featureName: 'Stablecoin Management · Quick actions', label: 'Quick Action — Wallet', selector: 'a.action-card--wallet', screen: SCREEN.dash, what: 'Navigation CTA to wallet balances and transaction history.', frontend: 'href="wallet-enhanced.html" (in duplicate: same folder).', backend: 'N/A — routing.' }),
  entry({ id: 'dashboard.actions.buyStablecoins', featureRow: 35, featureName: 'Stablecoin Management · Quick actions', label: 'Quick Action — Buy stablecoins', selector: 'a.action-card.primary[aria-label*="Buy stablecoins"]', screen: SCREEN.dash, what: 'Primary CTA to fiat/crypto on-ramp (get-unera-cad.html).', frontend: 'handleActionClick(Stablecoin/get-unera-cad.html) — checks KYC/wallet gates.', backend: 'N/A — navigation; gates use kycStatus / wallet bind state.' }),
  entry({ id: 'dashboard.actions.exchange', featureRow: 35, featureName: 'Stablecoin Management · Quick actions', label: 'Quick Action — Exchange', selector: 'a.action-card--exchange', screen: SCREEN.dash, what: 'CTA to token swap flow.', frontend: 'href / handleActionClick → exchange.html', backend: 'N/A' }),
  entry({ id: 'dashboard.actions.exploreCentres', featureRow: 35, featureName: 'Stablecoin Management · Quick actions', label: 'Quick Action — Explore Centres', selector: 'a.action-card--explore', screen: SCREEN.dash, what: 'CTA to HC directory (adjacent to donations, out of row 44 scope).', frontend: 'href="explore-centres.html"', backend: 'N/A' }),
  entry({ id: 'dashboard.actions.uneraCadHub', featureRow: 35, featureName: 'Stablecoin Management · Quick actions', label: 'UNERA CAD hub card', selector: '.unera-cad-hub-card', screen: SCREEN.dash, what: 'Entity-scoped hub for Get/Redeem UNERA CAD (Stablecoin app partition).', frontend: 'Links to Stablecoin/get-unera-cad.html, Stablecoin/redeem-unera-cad.html', backend: 'N/A' }),
  entry({ id: 'dashboard.activity.item.typeBadge', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Activity type badge (row 1)', selector: '.activity-list .activity-item:first-child .activity-type-badge', screen: SCREEN.dash, what: 'Transaction category chip (Donation, Yield, Send, etc.) for scanability.', frontend: 'Prototype: static HTML. Production: transaction.category → badge component map.', backend: 'GET /api/transactions?limit=5 → [{ "category": "donation", … }]', example: { category: 'donation', label: 'Donation' } }),
  entry({ id: 'dashboard.activity.item.title', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Activity title (row 1)', selector: '.activity-list .activity-item:first-child .activity-title', screen: SCREEN.dash, what: 'Human-readable activity headline.', frontend: 'transaction.title or template from type + counterparty.', backend: 'transactions[].title', example: 'Donation to Nairobi Humanity Centre' }),
  entry({ id: 'dashboard.activity.item.description', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Activity description (row 1)', selector: '.activity-list .activity-item:first-child .activity-description', screen: SCREEN.dash, what: 'Optional narrative line for impact context.', frontend: 'transaction.description or generated copy.', backend: 'transactions[].description', example: 'Your donation helped provide meals…' }),
  entry({ id: 'dashboard.activity.item.meta.time', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Activity timestamp (row 1)', selector: '.activity-list .activity-item:first-child .activity-meta span:first-child', screen: SCREEN.dash, what: 'Relative or absolute timestamp.', frontend: 'formatRelativeTime(transaction.createdAt) — same helper as notifications.', backend: 'ISO8601 createdAt', example: { createdAt: '2026-05-20T08:00:00Z' } }),
  entry({ id: 'dashboard.activity.item.meta.currency', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Activity currency (row 1)', selector: '.activity-list .activity-item:first-child .activity-meta span:last-child', screen: SCREEN.dash, what: 'Asset ticker for the activity row.', frontend: 'transaction.currency (hCAD, hUSD, …)', backend: 'transactions[].currency', example: { currency: 'hCAD' } }),
  entry({ id: 'dashboard.activity.item.amount', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Activity amount (row 1)', selector: '.activity-list .activity-item:first-child .activity-amount-value', screen: SCREEN.dash, what: 'Signed amount display; green positive for inflows/donations display convention.', frontend: 'Format with sign + --fin-up / --fin-down classes.', backend: 'transactions[].amount, direction', example: { amount: 250, direction: 'out', display: '+$250.00' } }),
  entry({ id: 'dashboard.activity.viewAll', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'View all activity', selector: '.activity-section .view-all-link', screen: SCREEN.dash, what: 'Deep link to full wallet transaction history.', frontend: 'href="wallet-enhanced.html#transaction-history"', backend: 'N/A' }),
  entry({ id: 'dashboard.notifications.badge', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Notification badge count', selector: '#notifBadge', screen: SCREEN.dash, what: 'Unread notification count on bell icon.', frontend: 'notifications.filter(n => !n.read).length from clb_notifications localStorage; seeded on dashboard load.', backend: 'GET /api/notifications/unread-count + WS push increment.', example: { unreadCount: 4 } }),
  entry({ id: 'dashboard.notifications.panel.item', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Bell panel — remittance (n5)', selector: '#notificationList .notif-item[data-id="n5"]', screen: SCREEN.dash, what: 'Remittance-type notification — surfaces transfer completion (row 37 + remittance cross-link).', frontend: 'Object in clb_notifications: { id, type:remittance, title, message, ctaUrl, ctaLabel }. Click marks read + navigates.', backend: 'GET /api/notifications + PATCH …/read; push via new_notification WS.', example: { id: 'n5', type: 'remittance', title: 'Remittance Sent', message: '25 CTC sent to family wallet — delivered on Polygon', read: false, ctaUrl: 'wallet-enhanced.html', ctaLabel: 'View transaction' } }),
  entry({ id: 'dashboard.notifications.panel.unreadDot', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Unread dot (bell panel)', selector: '#notificationList .notif-item:not(.read) .notif-unread-dot', screen: SCREEN.dash, what: 'Visual unread indicator per notification row.', frontend: 'Rendered when read === false.', backend: 'notifications[].read', example: { read: false } }),
  entry({ id: 'dashboard.nav.walletLink', featureRow: 35, featureName: 'Stablecoin Management · Quick actions', label: 'Nav — Wallet link', selector: '.nav-link[href*="wallet-enhanced"]', screen: SCREEN.dash, what: 'Persistent nav entry to wallet.', frontend: 'Static nav href', backend: 'N/A' }),
  entry({ id: 'dashboard.kyc.alertBanner', label: 'KYC alert banner', status: 'partial', selector: '#kycAlert', screen: SCREEN.dash, what: 'KYC status banner when unverified (adjacent gate for rows 35, 39).', frontend: 'Shown when localStorage.kycStatus !== verified', backend: 'GET /api/users/me → kycStatus', example: { kycStatus: 'pending' } }),
  // DASH-31–38: yield/donations/lives info tooltips + activity rows 2–3
  entry({ id: 'dashboard.impact.yield.infoTooltip', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Yield info (i)', selector: '.impact-card[aria-label*="Yield generated"] .info-tooltip', screen: SCREEN.dash, what: 'Product info tooltip explaining yield KPI semantics.', frontend: 'data-tooltip: Yield generated from your stablecoin reserves - 100% goes to impact', backend: 'N/A — copy deck.', example: 'Yield generated from your stablecoin reserves - 100% goes to impact' }),
  entry({ id: 'dashboard.impact.yield.sparkline', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Yield sparkline', selector: '.impact-card[aria-label*="Yield generated"] .impact-sparkline', screen: SCREEN.dash, what: 'Mini trend line for yield accrual over time.', frontend: 'Static SVG in prototype; production from yield history API.', backend: 'GET /api/yield/history?range=30d', example: { points: [{ date: '2026-05-19', value: 486.5 }] } }),
  entry({ id: 'dashboard.impact.donations.infoTooltip', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Donations info (i)', selector: '.impact-card[aria-label*="Total donations"] .info-tooltip', screen: SCREEN.dash, what: 'Product info tooltip for lifetime donations KPI.', frontend: 'data-tooltip: Total amount donated to Humanity Centres', backend: 'N/A — copy deck.', example: 'Total amount donated to Humanity Centres' }),
  entry({ id: 'dashboard.impact.donations.sparkline', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Donations sparkline', selector: '.impact-card[aria-label*="Total donations"] .impact-sparkline', screen: SCREEN.dash, what: 'Visual trend for donation velocity.', frontend: 'Static SVG; production maps donation history.', backend: 'GET /api/donations/history?range=30d', example: { points: [{ date: '2026-05-19', value: 5240 }] } }),
  entry({ id: 'dashboard.impact.lives.infoTooltip', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Lives impacted info (i)', selector: '.impact-card[aria-label*="Lives impacted"] .info-tooltip', screen: SCREEN.dash, what: 'Explains model-driven lives impacted estimate.', frontend: 'data-tooltip: Estimated number of lives positively impacted by your contributions', backend: 'N/A — copy deck.', example: 'Estimated number of lives positively impacted by your contributions' }),
  entry({ id: 'dashboard.activity.row2.title', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Activity title (row 2 — Yield)', selector: '.activity-list .activity-item:nth-child(2) .activity-title', screen: SCREEN.dash, what: 'Second activity row — yield accrual headline.', frontend: 'Static Yield Generated; production from transactions feed.', backend: 'transactions[].title', example: 'Yield Generated' }),
  entry({ id: 'dashboard.activity.row2.amount', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Activity amount (row 2)', selector: '.activity-list .activity-item:nth-child(2) .activity-amount-value', screen: SCREEN.dash, what: 'Yield amount with positive styling.', frontend: 'amount--positive class; format currency.', backend: 'transactions[].amount', example: { amount: 42.5, display: '+$42.50' } }),
  entry({ id: 'dashboard.activity.row3.title', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Activity title (row 3 — Donation)', selector: '.activity-list .activity-item:nth-child(3) .activity-title', screen: SCREEN.dash, what: 'Third activity row — donation to Toronto HC.', frontend: 'Static copy; maps to donation category.', backend: 'transactions[].title', example: 'Donation to Toronto HC' }),
  entry({ id: 'dashboard.activity.row3.meta', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Activity meta (row 3)', selector: '.activity-list .activity-item:nth-child(3) .activity-meta', screen: SCREEN.dash, what: 'Timestamp and asset ticker for row 3.', frontend: 'Relative time + currency span.', backend: 'createdAt, currency', example: { createdAt: '2026-05-17T12:00:00Z', currency: 'hUSD' } }),
];

function assetWalletEntries(symbol, balanceId, featureRows = [33, 36]) {
  const sym = symbol;
  const rows = featureRows;
  return [
    entry({ id: `wallet.asset.${sym}.balance`, featureRow: rows[0], featureName: 'Stablecoin Management · Balance display', label: `${sym} balance`, selector: `#${balanceId}`, screen: SCREEN.wallet, what: `${sym} token balance (display units + ticker).`, frontend: `#${balanceId} text; privacy blur via .balance-amount.hidden`, backend: `balances.accounts[] where symbol=${sym}`, example: { symbol: sym, amount: sym === 'hUSD' ? '2500.00' : sym === 'hEUR' ? '1250.00' : '425.50', fiatCad: sym === 'hUSD' ? 2500 : 1250 } }),
    entry({ id: `wallet.asset.${sym}.fiat`, featureRow: rows[0], featureName: 'Stablecoin Management · Balance display', label: `${sym} fiat equivalent`, selector: `[data-asset="${sym}"] .portfolio-asset-row-fiat`, screen: SCREEN.wallet, what: 'Fiat equivalent + cross-rate hint.', frontend: 'Computed from FX service', backend: 'balances.accounts[].fiat + fxRate', example: { fiatCad: 2500, fiatUsd: 1850 } }),
    entry({ id: `wallet.asset.${sym}.change7d`, featureRow: rows[1], featureName: 'Stablecoin Management · Visual summaries', label: `${sym} 7d change`, selector: `[data-asset="${sym}"] .balance-change`, screen: SCREEN.wallet, what: '7-day balance delta for asset row.', frontend: 'data-tooltip native + --fin-up styling', backend: 'GET /api/wallet/balances?includeChange=7d', example: { changePct7d: 2.5 } }),
    entry({ id: `wallet.asset.${sym}.allocationPct`, featureRow: rows[1], featureName: 'Stablecoin Management · Visual summaries', label: `${sym} allocation %`, selector: `[data-asset="${sym}"] .portfolio-asset-row-pct`, screen: SCREEN.wallet, what: 'Percent of total portfolio in this asset.', frontend: 'amount / portfolioTotal * 100', backend: 'Server-calculated allocationPct', example: { allocationPct: 30.3 } }),
    entry({ id: `wallet.asset.${sym}.sendAction`, featureRow: 35, featureName: 'Stablecoin Management · Quick actions', label: `${sym} Send CTA`, selector: `[data-asset="${sym}"] a[href*="send-enhanced"]`, screen: SCREEN.wallet, what: 'Per-asset Send CTA — deep link to remittance with asset query.', frontend: `send-enhanced.html?asset=${sym}`, backend: 'N/A', seeAlso: ['send.method.external'] }),
  ];
}

/** @type {ReturnType<typeof entry>[]} */
const wallet = [
  entry({ id: 'wallet.impact.totalDonations', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'Wallet — total donations', selector: '.impact-summary-wallet .impact-stat-mini:first-child .stat-value', screen: SCREEN.wallet, what: 'Mini impact stat — total donations from wallet context.', frontend: 'Static in HTML section .impact-summary-wallet', backend: 'GET /api/donations/summary', example: { totalFiat: 5240 } }),
  entry({ id: 'wallet.impact.centresSupported', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'Centres supported', selector: '.impact-stat-mini:nth-child(2) .stat-value', screen: SCREEN.wallet, what: 'Count of Humanity Centres supported.', frontend: 'Static 3', backend: 'donations.summary.centresCount', example: { centresCount: 3 } }),
  entry({ id: 'wallet.impact.lives', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Lives impacted (wallet)', selector: '.impact-stat-mini:nth-child(3) .stat-value', screen: SCREEN.wallet, what: 'Lives impacted estimate on wallet page.', frontend: 'Static 120+', backend: 'GET /api/impact/lives', example: { estimate: 120 } }),
  entry({ id: 'wallet.portfolio.total', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'Portfolio total', selector: '#portfolioTotal', screen: SCREEN.wallet, what: 'Authoritative total portfolio on wallet (more detailed than dashboard KPI).', frontend: 'Static $8,250.00; production balances API sum.', backend: 'GET /api/wallet/balances → portfolio.totalFiat', example: { totalFiat: 8250, currency: 'CAD' }, seeAlso: ['dashboard.impact.portfolio.value'] }),
  entry({ id: 'wallet.portfolio.change', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'Portfolio change %', selector: '.summary-stat-card:first-child .stat-change', screen: SCREEN.wallet, what: 'Portfolio period change percentage.', frontend: 'Derived from history; class positive → --fin-up', backend: 'portfolio.changePct7d', example: { changePct7d: 3.2 } }),
  entry({ id: 'wallet.portfolio.trustChip', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'Portfolio trust chip', selector: '.portfolio-trust-chip', screen: SCREEN.wallet, what: 'Trust signal — reserves backing copy.', frontend: 'Static copy + icon', backend: 'Optional link to PoR public page stats' }),
  entry({ id: 'wallet.asset.hCAD.balance', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'hCAD balance', selector: '#hcadBalance', screen: SCREEN.wallet, what: 'hCAD token balance (display units + ticker).', frontend: '#hcadBalance text; privacy blur via .balance-amount.hidden', backend: 'balances.accounts[] where symbol=hCAD', example: { symbol: 'hCAD', amount: '3500.00', fiatCad: 3500 } }),
  entry({ id: 'wallet.asset.hCAD.fiat', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'hCAD fiat equivalent', selector: '[data-asset="hCAD"] .portfolio-asset-row-fiat', screen: SCREEN.wallet, what: 'Fiat equivalent + cross-rate hint.', frontend: 'Computed from FX service', backend: 'balances.accounts[].fiat + fxRate', example: { fiatCad: 3500, fiatUsd: 2600 } }),
  entry({ id: 'wallet.asset.hCAD.change7d', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'hCAD 7d change', selector: '[data-asset="hCAD"] .balance-change', screen: SCREEN.wallet, what: '7-day balance delta for asset row.', frontend: 'data-tooltip native + --fin-up styling', backend: 'GET /api/wallet/balances?includeChange=7d', example: { changePct7d: 2.5 } }),
  entry({ id: 'wallet.asset.hCAD.allocationPct', featureRow: 36, featureName: 'Stablecoin Management · Visual summaries', label: 'hCAD allocation %', selector: '[data-asset="hCAD"] .portfolio-asset-row-pct', screen: SCREEN.wallet, what: 'Percent of total portfolio in this asset.', frontend: 'amount / portfolioTotal * 100', backend: 'Server-calculated allocationPct', example: { allocationPct: 42.4 } }),
  entry({ id: 'wallet.asset.hCAD.sendAction', featureRow: 35, featureName: 'Stablecoin Management · Quick actions', label: 'hCAD Send CTA', selector: '[data-asset="hCAD"] a[href*="send-enhanced"]', screen: SCREEN.wallet, what: 'Per-asset Send CTA — deep link to remittance with asset query.', frontend: 'send-enhanced.html?asset=hCAD', backend: 'N/A' }),
  ...assetWalletEntries('hUSD', 'husdBalance'),
  ...assetWalletEntries('hEUR', 'heurBalance'),
  ...assetWalletEntries('HUMA', 'humaBalance', [33, 36]),
  entry({ id: 'wallet.privacy.toggle', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'Privacy toggle', selector: '#privacyToggle', screen: SCREEN.wallet, what: 'Hide/show balance amounts client-side for privacy.', frontend: 'toggleBalancePrivacy() toggles .balance-amount.hidden; persist localStorage.balanceHidden', backend: 'N/A — client preference PATCH /api/users/preferences optional', example: { balanceHidden: true } }),
  entry({ id: 'wallet.quickActions.buy', featureRow: 35, featureName: 'Stablecoin Management · Quick actions', label: 'Wallet — Buy', selector: '.quick-actions a[href*="get-unera-cad"], .quick-actions button[onclick*="get-unera-cad"]', screen: SCREEN.wallet, what: 'Wallet-level buy stablecoins action.', frontend: 'Link to Stablecoin get flow', backend: 'N/A' }),
  entry({ id: 'wallet.quickActions.send', featureRow: 35, featureName: 'Stablecoin Management · Quick actions', label: 'Wallet — Send', selector: '.quick-actions a[href*="send-enhanced"]', screen: SCREEN.wallet, what: 'Wallet-level send/remittance entry.', frontend: 'send-enhanced.html', backend: 'N/A', seeAlso: ['send.method.external'] }),
  entry({ id: 'wallet.history.search', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'History search', selector: '#searchInput', screen: SCREEN.wallet, what: 'Client-side filter across visible transaction rows; prod uses query param.', frontend: 'searchTransactions() filters DOM; prod: debounce → GET /api/transactions?search=', backend: 'GET /api/transactions?search=alice' }),
  entry({ id: 'wallet.history.filters.button', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Filter button', selector: '#filterBtn', screen: SCREEN.wallet, what: 'Opens filter modal — type, status, currency, date range.', frontend: 'activeFilters object in page JS; presets in walletFilterPresets localStorage', backend: 'Query params on transactions API', example: { status: ['pending'], currency: 'hCAD' } }),
  entry({ id: 'wallet.history.row.status', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Tx status (pending row)', selector: '#transactionList .transaction-item:nth-child(3) .transaction-status', screen: SCREEN.wallet, what: 'Status label on row (Completed / Pending / Failed) — use tx003 pending row.', frontend: 'Static HTML class .transaction-status.pending', backend: 'transactions[].status enum: completed|pending|failed|cancelled', example: { id: 'tx003', status: 'pending', title: 'Bank Transfer In' } }),
  entry({ id: 'wallet.history.row.amount', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Tx amount (row 1)', selector: '#transactionList .transaction-item:nth-child(1) .amount-primary', screen: SCREEN.wallet, what: 'Primary amount column with direction color.', frontend: 'Classes positive|negative|neutral', backend: 'amount, direction', example: { amount: 500, direction: 'in' } }),
  entry({ id: 'wallet.history.row.remittance', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Remittance row (tx005)', selector: '#transactionList .transaction-item[aria-label*="Sent"]', screen: SCREEN.wallet, what: 'Remittance/send row example (tx005 Bob Chen).', frontend: 'Static row; category sent / remittance', backend: 'GET /api/transactions?category=remittance', example: { category: 'remittance', counterparty: 'Bob Chen' } }),
  entry({
    id: 'wallet.history.planned.tabsHub',
    featureRow: 38,
    featureName: 'Stablecoin Management · Donation + remittance history hub',
    label: 'Planned — History tabs hub',
    status: 'planned',
    selector: '.history-section .section-header, .history-section #transactionList',
    screen: SCREEN.wallet,
    what: 'PLANNED: Tab strip above history — All | Remittances | Donations — filtering one ledger without separate pages.',
    frontend: 'Tab → set activeFilters.categories or ?category=remittance|donation. Today: single list + manual filter chip only.',
    backend: 'GET /api/transactions?category=remittance|donation|all',
    example: { category: 'remittance', total: 42 },
    presenterNote: 'Row 38 gap — no tabs in current UI. This tooltip documents the planned hub.',
  }),
  entry({ id: 'wallet.history.detail.transactionId', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Detail — transaction ID', selector: '#transactionList .transaction-item[onclick*="tx001"]', screen: SCREEN.wallet, what: 'Unique transaction identifier in side sheet (open tx001 first).', frontend: 'showTransactionDetail(tx001) populates sheet', backend: 'GET /api/transactions/tx001', example: { id: 'tx001', externalRef: 'TX-2026-001' }, presenterNote: 'Click tx001 row before hovering.' }),
  entry({ id: 'wallet.history.export.button', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Export results', selector: '#exportContainer .export-btn', screen: SCREEN.wallet, what: 'Export filtered transaction list to CSV/PDF.', frontend: 'showExportDialog() when filters active; exportContainer shown after filter apply', backend: 'GET /api/transactions/export?format=csv&…', example: { format: 'csv', rowCount: 10 } }),
  entry({ id: 'wallet.history.loadMore', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Load more transactions', selector: '#loadMoreBtn', screen: SCREEN.wallet, what: 'Pagination sentinel — loads next page of history.', frontend: 'loadMoreTransactions() appends rows; scrollSentinel for infinite scroll', backend: 'GET /api/transactions?cursor=…', example: { shown: 10, total: 15 } }),
  entry({ id: 'wallet.history.dateGroup.header', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Date group header', selector: '#transactionList .date-header:first-child', screen: SCREEN.wallet, what: 'Groups transactions by day (Today, Yesterday, …).', frontend: 'Static date headers in prototype; production groups by createdAt date', backend: 'Server may return grouped sections', example: 'Today' }),
  entry({ id: 'wallet.history.activeFilters', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Active filter chips', selector: '#activeFilters', screen: SCREEN.wallet, what: 'Removable chips summarizing applied filters.', frontend: 'Rendered when activeFilters has selections; clear via chip dismiss', backend: 'Mirrors query params sent to transactions API', example: { status: ['pending'], currency: 'hCAD' } }),
  entry({ id: 'wallet.history.detail.fee', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Detail — fee line', selector: '#transactionList .transaction-item:nth-child(1) .transaction-meta', screen: SCREEN.wallet, what: 'Network/fiat fee on transaction detail (when sheet opens).', frontend: 'Populated in showTransactionDetail from mock tx object', backend: 'transactions[].fee', example: { fee: 0, currency: 'CAD' }, presenterNote: 'Detail sheet is JS-driven; hover row after opening detail if implemented.' }),
  entry({ id: 'wallet.history.detail.network', featureRow: 34, featureName: 'Stablecoin Management · Recent transactions', label: 'Detail — network', selector: '#transactionList .transaction-item[onclick*="tx005"]', screen: SCREEN.wallet, what: 'Chain/network for on-chain remittance rows.', frontend: 'Static meta on remittance row', backend: 'transactions[].network', example: { network: 'polygon', txHash: '0xabc…' } }),
];

/** @type {ReturnType<typeof entry>[]} */
const notifications = [
  entry({ id: 'notifications.page.title', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Inbox page title', selector: '.page-title', screen: SCREEN.notif, what: 'Inbox page heading.', frontend: 'Static', backend: 'N/A' }),
  entry({ id: 'notifications.tabs.all', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Tab — All', selector: '.tabs .tab.active', screen: SCREEN.notif, what: 'Filter tab — show all notification types.', frontend: 'filterNotifications(all)', backend: 'Client filter on array; prod GET /api/notifications' }),
  entry({ id: 'notifications.tabs.remittance', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Tab — Remittances', selector: '.tabs .tab[onclick*="remittance"]', screen: SCREEN.notif, what: 'Filter to remittance-type alerts only.', frontend: 'Filter where type === remittance', backend: 'GET /api/notifications?type=remittance' }),
  entry({ id: 'notifications.tabs.transaction', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Tab — Transactions', selector: '.tabs .tab[onclick*="transaction"]', screen: SCREEN.notif, what: 'Filter to generic transaction confirmations.', frontend: 'type === transaction', backend: 'Query param filter' }),
  entry({ id: 'notifications.item.n5.title', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'n5 — title', selector: '#notification-list li[data-id="n5"] .notification-card-title, #notification-list [data-id="n5"]', screen: SCREEN.notif, what: 'Remittance notification headline.', frontend: 'From DEFAULT_NOTIFICATIONS seed / clb_notifications', backend: 'notifications[].title', example: 'Remittance Sent' }),
  entry({ id: 'notifications.item.n5.message', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'n5 — message', selector: '#notification-list [data-id="n5"] .notification-card-message', screen: SCREEN.notif, what: 'Body copy — amount, asset, network delivery detail.', frontend: 'message field', backend: 'Push payload from remittance service on status=delivered', example: '25 CTC sent to family wallet — delivered on Polygon' }),
  entry({ id: 'notifications.item.n5.cta', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'n5 — CTA', selector: '#notification-list [data-id="n5"] a.notification-card-cta, #notification-list [data-id="n5"]', screen: SCREEN.notif, what: 'Deep link CTA to wallet history.', frontend: 'ctaUrl: wallet-enhanced.html, ctaLabel: View transaction', backend: 'notifications[].ctaUrl / ctaLabel', example: { ctaUrl: 'wallet-enhanced.html', ctaLabel: 'View transaction' } }),
  entry({ id: 'notifications.item.n1.transaction', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'n1 — transaction confirmed', selector: '#notification-list [data-id="n1"]', screen: SCREEN.notif, what: 'On-chain transaction confirmed alert.', frontend: 'type: transaction', backend: 'Created when tx reaches confirmed', example: { type: 'transaction', title: 'Transaction Confirmed' } }),
  entry({ id: 'notifications.item.timestamp', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Relative timestamp', selector: '.notification-card .notification-card-time, #notification-list .notification-card-time', screen: SCREEN.notif, what: 'Relative time display.', frontend: 'formatRelativeTime(iso) — dashboard shares helper', backend: 'ISO8601 timestamp', example: { timestamp: '2026-05-15T12:00:00Z' } }),
  entry({ id: 'notifications.item.readState', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Read state styling', selector: '.notification-card.unread', screen: SCREEN.notif, what: 'Read vs unread styling + badge eligibility.', frontend: 'read: true|false; toggle on click', backend: 'PATCH /api/notifications/{id}/read', example: { read: false } }),
  entry({ id: 'notifications.emptyState', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Empty state', selector: '#empty-state', screen: SCREEN.notif, what: 'Zero-notification UX.', frontend: 'Shown when filtered list empty', backend: 'N/A' }),
  entry({ id: 'notifications.markAllRead', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Mark all read', selector: '.bulk-actions button[onclick*="markAllNotificationsRead"]', screen: SCREEN.notif, what: 'Bulk action — mark entire inbox read.', frontend: 'markAllNotificationsRead(); renderPageList()', backend: 'PATCH /api/notifications/mark-all-read' }),
  entry({ id: 'notifications.clearAll', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Clear all', selector: '.bulk-actions button[onclick*="clearAllNotifications"]', screen: SCREEN.notif, what: 'Removes all notifications from client store.', frontend: 'clearAllNotifications(); renderPageList()', backend: 'DELETE /api/notifications (proposed)' }),
  entry({ id: 'notifications.typeIcon.remittance', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Type icon — remittance', selector: '.notification-card.remittance .notification-card-icon', screen: SCREEN.notif, what: 'Visual type discriminator for remittance alerts.', frontend: 'CSS .notification-card.remittance::before accent', backend: 'notifications[].type drives icon map' }),
  entry({ id: 'notifications.tabs.verification', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Tab — Verification', selector: '.tabs .tab[onclick*="verification"]', screen: SCREEN.notif, what: 'KYC/identity verification notifications filter.', frontend: 'filterNotifications(verification)', backend: 'GET /api/notifications?type=verification' }),
  entry({ id: 'notifications.tabs.system', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Tab — Security', selector: '.tabs .tab[onclick*="system"]', screen: SCREEN.notif, what: 'Security/system alerts filter.', frontend: 'filterNotifications(system)', backend: 'GET /api/notifications?type=system' }),
  entry({ id: 'notifications.tabs.unread', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Tab — Unread', selector: '.tabs .tab[onclick*="unread"]', screen: SCREEN.notif, what: 'Shows only unread notifications.', frontend: 'filterNotifications(unread)', backend: 'GET /api/notifications?read=false' }),
  entry({ id: 'notifications.tabs.donation', featureRow: 37, featureName: 'Stablecoin Management · Transaction status alerts', label: 'Tab — Donations', selector: '.tabs .tab[onclick*="donation"]', screen: SCREEN.notif, what: 'Donation-type notification filter.', frontend: 'filterNotifications(donation)', backend: 'GET /api/notifications?type=donation' }),
];

/** @type {ReturnType<typeof entry>[]} */
const send = [
  entry({ id: 'send.prereq.kyc', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'KYC prerequisite', selector: '#kycAction, #stepPrereq .prereq-item:first-child', screen: SCREEN.send, what: 'KYC verification gate before send.', frontend: 'appState.kycVerified = localStorage.kycStatus === verified', backend: 'GET /api/users/me → kycStatus: verified|pending|rejected', example: { kycStatus: 'verified' } }),
  entry({ id: 'send.prereq.wallet', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Wallet prerequisite', selector: '#walletAction', screen: SCREEN.send, what: 'Wallet connection gate.', frontend: 'appState.walletConnected = !!localStorage.walletAddress', backend: 'GET /api/wallet/primary or bind endpoint', example: { walletConnected: true } }),
  entry({ id: 'send.method.unera', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Method — UNERA user', selector: '.send-option[data-option="unera"]', screen: SCREEN.send, what: 'Rail: send to registered UNERA user by email.', frontend: 'Sets appState.sendOption = unera; fee = 0', backend: 'POST /api/transfers/internal', example: { rail: 'unera_user', fee: 0 } }),
  entry({ id: 'send.method.external', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Method — External wallet', selector: '.send-option[data-option="external"]', screen: SCREEN.send, what: 'Rail: on-chain send to external wallet (row 39 primary).', frontend: 'appState.sendOption = external; fee = $2.50 flat in mock', backend: 'POST /api/remittance/send + chain broadcast', example: { rail: 'external_wallet', fee: 2.5 } }),
  entry({ id: 'send.method.bank', featureRow: 40, featureName: 'Stablecoin Remittance · Payee (bank)', label: 'Method — Bank withdrawal', selector: '.send-option[data-option="bank"]', screen: SCREEN.send, what: 'Rail: fiat withdrawal to saved bank account.', frontend: 'appState.sendOption = bank; fee = 1% min $1', backend: 'POST /api/withdrawals/bank', example: { rail: 'bank', feePct: 1, feeMin: 1 } }),
  entry({ id: 'send.external.network.ethereum', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Network — Ethereum', selector: '#step3Card .network-card:first-child', screen: SCREEN.send, what: 'Target chain selection — determines address format & fees.', frontend: 'selectNetwork(Ethereum) → appState.selectedNetwork', backend: 'GET /api/chains/supported + quote uses network', example: { network: 'ethereum', chainId: 1 }, presenterNote: 'Select External + Continue to step 3 first.' }),
  entry({ id: 'send.external.network.grid', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Network grid', selector: '#step3Card .network-grid', screen: SCREEN.send, what: 'Full network picker (Ethereum, BNB, Polygon, Arbitrum).', frontend: 'Injected HTML in renderStep3()', backend: 'Supported networks list from config service', example: { networks: ['ethereum', 'bnb', 'polygon', 'arbitrum'] }, presenterNote: 'Select External + Continue to step 3 first.' }),
  entry({ id: 'send.external.address.input', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Wallet address input', selector: '#walletAddress', screen: SCREEN.send, what: 'Destination wallet address (checksummed hex or compatible).', frontend: 'updateWalletAddress() → appState.walletAddress', backend: 'Validated server-side; stored on transfer as toAddress', example: { toAddress: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F' }, presenterNote: 'Select External + Continue to step 3 first.' }),
  entry({ id: 'send.external.address.validBadge', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Address verified badge', selector: '#addressVerifiedBadge', screen: SCREEN.send, what: 'Client-side format validation feedback only — not on-chain checksum proof.', frontend: 'checkAddressFormat() — shows if length ≥ 20 and starts with 0x', backend: 'Server validates EIP-55 checksum before submit' }),
  entry({
    id: 'send.external.planned.savedWallets',
    featureRow: 41,
    featureName: 'Stablecoin Remittance · Wallet payee book',
    label: 'Planned — Saved wallets',
    status: 'planned',
    selector: '#step3Card .section-title, #step3Card',
    screen: SCREEN.send,
    what: 'PLANNED: Saved Wallets panel — .saved-methods-list pattern mirroring bank branch. Rows: label, network chip, truncated address, Send again.',
    frontend: 'GET /api/payees/wallets → render cards; select → prefills #walletAddress + network. Save this wallet checkbox on confirm step.',
    backend: 'GET /api/payees/wallets; POST /api/payees/wallets',
    example: { payees: [{ id: 'wp_1', label: 'Cousin — Base USDC', network: 'base', addressMasked: '0x71C7…976F', lastUsedAt: '2026-05-01T10:00:00Z' }] },
    presenterNote: 'Row 41 — UI not built. Tooltip anchored to external wallet section title.',
  }),
  entry({ id: 'send.amount.availableBalance', featureRow: 39, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Available balance', selector: '#availableBalance', screen: SCREEN.send, what: 'Spendable balance for selected primary currency (appState.primaryCurrency default hUSD).', frontend: 'appState.balances[primaryCurrency] formatted in goToStep(4)', backend: 'GET /api/wallet/balances → available minus pending holds', example: { available: 2500, currency: 'hUSD' } }),
  entry({ id: 'send.amount.input', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Amount input', selector: '#amountInput', screen: SCREEN.send, what: 'User-entered send amount (display currency).', frontend: 'validateAmount() → appState.amount; max = available', backend: 'Validated against limits on POST /api/remittance/send', example: { amount: 100, currency: 'hUSD' } }),
  entry({ id: 'send.amount.feePreview', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Fee preview', selector: '#feePreview', screen: SCREEN.send, what: 'Estimated fee before review — $0 unera, $2.50 external, 1% bank.', frontend: 'Computed in validateAmount() from sendOption', backend: 'GET /api/remittance/quote returns authoritative fee', example: { fee: 2.5, feeCurrency: 'USD' } }),
  entry({ id: 'send.amount.usdEquiv', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'USD equivalent', selector: '#sendUsdEquivVal', screen: SCREEN.send, what: 'FX equivalent hint under amount field.', frontend: 'Client FX rate table in JS', backend: 'Quote service FX rate', example: { amountUsd: 100 } }),
  entry({ id: 'send.review.type', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Review — send type', selector: '#reviewType', screen: SCREEN.send, what: 'Human label for selected rail on review step.', frontend: 'Populated in goToStep(5) from appState.sendOption', backend: 'Response echo rail', example: 'External Wallet', presenterNote: 'Advance to step 5 with sample amount $100.' }),
  entry({ id: 'send.review.destination', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Review — destination', selector: '#reviewDestination', screen: SCREEN.send, what: 'Recipient summary — address + network or bank mask.', frontend: 'Built from appState.walletAddress + selectedNetwork or bank method', backend: 'toAddress, network on transfer record', example: { toAddress: '0x71C7…', network: 'ethereum' } }),
  entry({ id: 'send.review.amount', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Review — amount', selector: '#reviewAmount', screen: SCREEN.send, what: 'Principal amount excl. fee.', frontend: 'appState.amount', backend: 'transfer.amount', example: { amount: 100 } }),
  entry({ id: 'send.review.fee', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Review — fee', selector: '#reviewFee', screen: SCREEN.send, what: 'Fee line item.', frontend: 'appState.fee', backend: 'transfer.fee', example: { fee: 2.5 } }),
  entry({ id: 'send.review.total', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Review — total', selector: '#reviewTotal', screen: SCREEN.send, what: 'Total debit = amount + fee (bank may differ).', frontend: 'amount + fee', backend: 'transfer.totalDebit', example: { total: 102.5 } }),
  entry({ id: 'send.review.note', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Review — note', selector: '#reviewNote', screen: SCREEN.send, what: 'Optional memo/reference.', frontend: 'appState.note', backend: 'transfer.memo', example: { memo: 'Family support May' } }),
  entry({
    id: 'send.review.planned.recipientReceives',
    featureRow: 42,
    featureName: 'Stablecoin Remittance · Crypto-to-crypto matching',
    label: 'Planned — Recipient receives',
    status: 'planned',
    selector: '#step5 .card, #step5 .section-title',
    screen: SCREEN.send,
    what: 'PLANNED: Recipient receives callout — e.g. 98.50 USDC on Base after route fees/slippage, quoted rate, ETA.',
    frontend: 'On entering step 5, call quote API with fromAsset=hUSD, toAsset=USDC, network=base, render card below summary items.',
    backend: 'GET /api/remittance/quote?fromAsset=hUSD&toAsset=USDC&network=base&amount=100',
    example: { send: { amount: 100, asset: 'hUSD' }, receive: { amount: '98.50', asset: 'USDC', network: 'base' }, rate: 0.985, slippageBps: 50, etaMinutes: 15, expiresAt: '2026-05-20T12:15:00Z' },
    presenterNote: 'Row 42 — card not in DOM. Advance to step 5; hover review card area.',
  }),
  entry({ id: 'send.processing.title', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Processing title', selector: '#step6 .processing-title', screen: SCREEN.send, what: 'In-flight state while backend/settlement runs.', frontend: 'Shown between confirm and success; processSend() timeout mock', backend: 'Async job; poll GET /api/remittance/{id} or WS', example: { status: 'processing' } }),
  entry({ id: 'send.success.amount', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Success amount', status: 'partial', selector: '#successAmount', screen: SCREEN.send, what: 'Confirmation hero amount — uses --fin-up per financial direction rules.', frontend: 'Set in processSend() success handler', backend: 'Final settled amount from transfer record', example: { amount: 100, currency: 'hUSD' } }),
  entry({ id: 'send.success.destination', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Success destination', status: 'partial', selector: '#successDestination', screen: SCREEN.send, what: 'Recipient echo on success screen.', frontend: 'Same as review destination', backend: 'transfer.toAddress' }),
  entry({ id: 'send.success.transactionId', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Success transaction ID', status: 'partial', selector: '#transactionId', screen: SCREEN.send, what: 'Internal transfer ID / receipt reference (not yet link to standalone receipt page).', frontend: 'Mock TX-2026-XXXX generated client-side', backend: 'POST /api/remittance/send → { id, txHash }', example: { id: 'TX-2026-001', txHash: '0xabc123…' } }),
  entry({ id: 'send.success.heroPattern', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Success hero pattern', status: 'partial', selector: '#step7 .success-icon-animated', screen: SCREEN.send, what: 'Success hero uses .success-state + #step7 — gap: canonical pattern is #step-complete + .success-screen.', frontend: 'Align DOM ids when product fix ships; data-mapping documents current state.', backend: 'N/A' }),
  entry({ id: 'send.bank.savedAccounts.header', featureRow: 40, featureName: 'Stablecoin Remittance · Payee (bank)', label: 'Saved accounts header', status: 'partial', selector: '#step3Card .withdrawal-methods-header', screen: SCREEN.send, what: 'Saved bank accounts section label + add-new affordance.', frontend: 'showAddBankMock() alert only — no real CRUD', backend: 'POST /api/payees/bank-accounts', presenterNote: 'Bank branch — step 2 → Bank → Continue.' }),
  entry({ id: 'send.bank.savedAccount.td', featureRow: 40, featureName: 'Stablecoin Remittance · Payee (bank)', label: 'Saved account — TD', status: 'partial', selector: '.saved-method-card[onclick*="bank_1"]', screen: SCREEN.send, what: 'Saved payee row — TD Canada Trust •••• 1234.', frontend: 'selectBankMethod(bank_1, …) → appState.selectedWithdrawalId', backend: 'GET /api/payees/bank-accounts', example: { id: 'bank_1', institution: 'TD Canada Trust', accountMask: '1234', currency: 'CAD' }, presenterNote: 'Bank branch — step 2 → Bank → Continue.' }),
  entry({ id: 'send.bank.savedAccount.rbc', featureRow: 40, featureName: 'Stablecoin Remittance · Payee (bank)', label: 'Saved account — RBC', status: 'partial', selector: '.saved-method-card[onclick*="bank_2"]', screen: SCREEN.send, what: 'Second saved bank row — RBC •••• 5678.', frontend: 'Same as TD card', backend: 'GET /api/payees/bank-accounts', example: { id: 'bank_2', institution: 'RBC Royal Bank' }, presenterNote: 'Bank branch — step 2 → Bank → Continue.' }),
  entry({ id: 'send.stepper.progress', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Stepper progress', selector: '#stepperProgress, .stepper', screen: SCREEN.send, what: 'Multi-step progress indicator — brand deep blue active step.', frontend: 'updateStepperAndMobile() from appState.currentStep', backend: 'N/A' }),
  entry({ id: 'send.unera.search', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'UNERA user search', selector: '#uneraSearch', screen: SCREEN.send, what: 'Search registered UNERA users by name or email.', frontend: 'searchUneraUser(value) filters recent list', backend: 'GET /api/users/search?q=', example: { query: 'bob', results: 1 } }),
  entry({ id: 'send.unera.recentContact.bob', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Recent contact — Bob', selector: '.recent-item[onclick*="Bob Chen"]', screen: SCREEN.send, what: 'Recent UNERA payee shortcut.', frontend: 'selectUneraUser(Bob Chen, bob@example.com)', backend: 'GET /api/transfers/recent', example: { name: 'Bob Chen', email: 'bob@example.com' } }),
  entry({ id: 'send.unera.recentContact.alice', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Recent contact — Alice', selector: '.recent-item[onclick*="Alice Johnson"]', screen: SCREEN.send, what: 'Recent UNERA payee shortcut.', frontend: 'selectUneraUser(Alice Johnson, alice@example.com)', backend: 'GET /api/transfers/recent', example: { name: 'Alice Johnson', email: 'alice@example.com' } }),
  entry({ id: 'send.unera.recentContact.maria', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Recent contact — Maria', selector: '.recent-item[onclick*="Maria Garcia"]', screen: SCREEN.send, what: 'Recent UNERA payee shortcut.', frontend: 'selectUneraUser(Maria Garcia, maria@example.com)', backend: 'GET /api/transfers/recent', example: { name: 'Maria Garcia', email: 'maria@example.com' } }),
  entry({ id: 'send.amount.presets', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Amount presets', selector: '.presets .preset-btn:first-child', screen: SCREEN.send, what: 'Quick amount chips ($50, $100, $250, $500).', frontend: 'setAmount(n) from preset buttons', backend: 'N/A — client only', example: { amount: 50 } }),
  entry({ id: 'send.amount.max', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Max amount button', selector: '.presets .preset-btn[onclick*="setMaxAmount"]', screen: SCREEN.send, what: 'Fills amount with available balance minus fee.', frontend: 'setMaxAmount() uses balance - fee', backend: 'Available from balances API', example: { max: 2497.5 } }),
  entry({ id: 'send.review.irreversibilityWarn', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Irreversibility warning', selector: '#step5 .unera-icon-lead--tone-error', screen: SCREEN.send, what: 'Warns transfer cannot be undone before confirm.', frontend: 'Static copy on review step with error-tone icon lead', backend: 'N/A — compliance copy', example: 'Once sent, this cannot be undone.' }),
  entry({ id: 'send.review.2faHint', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: '2FA hint', selector: '#step5 .unera-icon-lead--tone-success', screen: SCREEN.send, what: 'Trust signal that 2FA is enabled for outbound transfers.', frontend: 'Static 2FA enabled copy on review card', backend: 'GET /api/users/me → mfaEnabled', example: { mfaEnabled: true } }),
  entry({ id: 'send.appState.balances', featureRow: 33, featureName: 'Stablecoin Management · Balance display', label: 'Mock balances object', selector: '#availableBalance', screen: SCREEN.send, what: 'Client mock balances driving send flow (L1957–1961).', frontend: 'appState.balances = { hCAD, hUSD, hEUR }', backend: 'GET /api/wallet/balances replaces mock', example: { hCAD: 2500, hUSD: 2500, hEUR: 1500 } }),
  entry({ id: 'send.external.network.bnb', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Network — BNB Chain', selector: '#step3Card .network-card[onclick*="BNB"]', screen: SCREEN.send, what: 'BNB Smart Chain network selection.', frontend: 'selectNetwork(BNB Chain)', backend: 'GET /api/chains/supported', example: { network: 'bnb', chainId: 56 }, presenterNote: 'Select External + Continue to step 3 first.' }),
  entry({ id: 'send.external.network.polygon', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Network — Polygon', selector: '#step3Card .network-card[onclick*="Polygon"]', screen: SCREEN.send, what: 'Polygon network selection.', frontend: 'selectNetwork(Polygon)', backend: 'GET /api/chains/supported', example: { network: 'polygon', chainId: 137 }, presenterNote: 'Select External + Continue to step 3 first.' }),
  entry({ id: 'send.external.network.arbitrum', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Network — Arbitrum', selector: '#step3Card .network-card[onclick*="Arbitrum"]', screen: SCREEN.send, what: 'Arbitrum network selection.', frontend: 'selectNetwork(Arbitrum)', backend: 'GET /api/chains/supported', example: { network: 'arbitrum', chainId: 42161 }, presenterNote: 'Select External + Continue to step 3 first.' }),
  entry({ id: 'send.mobile.stepper', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Mobile stepper', selector: '.mobile-stepper-compact', screen: SCREEN.send, what: 'Compact step indicator on narrow viewports.', frontend: 'updateStepperAndMobile() syncs with desktop stepper', backend: 'N/A' }),
  entry({ id: 'send.step2.continue', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Step 2 continue', selector: '#step2 .btn-primary', screen: SCREEN.send, what: 'Advances from method selection to recipient step.', frontend: 'goToStep(3) after sendOption set', backend: 'N/A' }),
  entry({ id: 'send.step4.continue', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Step 4 continue', selector: '#step4 .btn-primary', screen: SCREEN.send, what: 'Validates amount and advances to review.', frontend: 'validateAmount() then goToStep(5)', backend: 'GET /api/remittance/quote (future)' }),
  entry({ id: 'send.confirm.button', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Confirm & Send', selector: '#step5 .btn-primary', screen: SCREEN.send, what: 'Submits transfer — triggers processing step.', frontend: 'processSend() mock async', backend: 'POST /api/remittance/send' }),
  entry({ id: 'send.success.viewWallet', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Back to Wallet CTA', selector: '#step7 .btn-secondary', screen: SCREEN.send, what: 'Post-success navigation to wallet history.', frontend: 'window.location.href wallet-enhanced.html', backend: 'N/A' }),
  entry({ id: 'send.success.sendAgain', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Send again', selector: '#step7 .btn-primary', screen: SCREEN.send, what: 'Resets flow for another transfer.', frontend: 'resetFlow()', backend: 'N/A' }),
  entry({ id: 'send.prereq.continue', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Prerequisites continue', selector: '#stepPrereq .btn-primary', screen: SCREEN.send, what: 'Unlocks send flow when KYC + wallet gates pass.', frontend: 'checkPrerequisites() sets prereqsMet', backend: 'Gates from GET /api/users/me and wallet bind' }),
  entry({ id: 'send.amount.note', featureRow: 43, featureName: 'Stablecoin Remittance · Transfer confirmation', label: 'Transfer note field', selector: '#noteInput', screen: SCREEN.send, what: 'Optional reference stored on transfer.', frontend: 'Bound to appState.note', backend: 'transfer.memo', example: { memo: 'Family support May' } }),
  entry({ id: 'send.bank.addNew', featureRow: 40, featureName: 'Stablecoin Remittance · Payee (bank)', label: 'Add bank (mock)', status: 'partial', selector: '#step3Card .withdrawal-methods-header button', screen: SCREEN.send, what: 'Add new bank account affordance — mock alert only.', frontend: 'showAddBankMock() — no CRUD', backend: 'POST /api/payees/bank-accounts (future)', presenterNote: 'Bank branch — step 2 → Bank → Continue.' }),
  entry({ id: 'send.step3.continue', featureRow: 39, featureName: 'Stablecoin Remittance · Send to wallet', label: 'Step 3 continue', selector: '#step3Card .btn-primary', screen: SCREEN.send, what: 'Validates recipient and advances to amount.', frontend: 'Enabled when address/network or bank selected', backend: 'N/A', presenterNote: 'Complete step 3 fields first.' }),
];

const entries = [...dashboard, ...wallet, ...notifications, ...send];

const catalog = {
  version: '1.0',
  round: 'token-mgmt-remittance',
  generatedAt: new Date().toISOString(),
  entryCount: entries.length,
  entries,
};

writeFileSync(OUT, JSON.stringify(catalog, null, 2) + '\n', 'utf8');

const counts = {
  dashboard: dashboard.length,
  wallet: wallet.length,
  notifications: notifications.length,
  send: send.length,
  total: entries.length,
};

console.log('Wrote', OUT);
console.log('Entry counts:', counts);

if (entries.length < 150) {
  console.error(`ERROR: expected ≥150 entries, got ${entries.length}`);
  process.exit(1);
}

const planned = entries.filter((e) => e.status === 'planned').map((e) => e.id);
console.log('Planned entries:', planned.join(', '));
